# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# u1= User.create!(username: 'Hassan', email: 'has@has.com', username: 'has', image: 'https://www.fillmurray.com/200/300' )
# u2= User.create!(username: 'Sah', email: 'sah@sah.com', username: 'Sah', image: 'https://www.fillmurray.com/200/300' )
Diet.create!([
  {
    name: "5:2 diet",
    intro: "The 5:2 diet is based on a principle known as intermittent fasting (IF) – where you eat normally for five days a week and fast on the other two days. On top of losing weight, fans claim the 5:2 diet can improve lifespan and brain function, and protect against conditions such as dementia and Alzheimer's disease.
    However, evidence on the effectiveness of the 5:2 diet is limited when compared with other types of weight loss techniques. One 2010 study found women placed on a 5:2 diet achieved similar levels of weight loss to women on a calorie-controlled diet, and were also less likely to develop chronic diseases such as type 2 diabetes. There is some evidence that the 5:2 model may help lower the risk of certain obesity-related cancers, such as breast cancer. ",
    pros: "Sticking to a regimen for two days a week is more achievable than seven days, so you are more likely to persevere with this way of eating and successfully lose weight. Two days a week on a restricted diet can lead to greater reductions in body fat, insulin resistance and other chronic diseases.",
    cons: "The non-restricted days do not mean unlimited feasting. While you don't need to be as strict about your calorie consumption, you still need to make healthy choices and be physically active.
    Skipping meals could make you feel dizzy, irritable, give you headaches and make it hard to concentrate, which can affect work and other daily tasks. Other reported side effects are difficulties sleeping and daytime sleepiness, bad breath, and dehydration.
    ",
    bda: "The 5:2 is a simple way to reduce calorie intake. There are lots of versions of this diet, with some less safe than others. Many studies on intermittent fasting are short-term, involve small numbers of subjects, or are animal-based. If you choose to follow it, choose an evidence-based plan based on healthy, balanced eating and written by a dietitian, such as the '2-Day Diet It's vital for your health to avoid nutritional deficiencies, dehydration and overeating on non-fast days. Never attempt to delay or skip meals if you are pregnant, have had, or are prone to eating disorders or diabetes"
  },{
    name: "Dukan diet",
    intro: "The Dukan diet is a low-carbohydrate (carb), high-protein diet. There's no limit to how much you can eat during the plan's four phases, provided you stick to the rules of the plan. During phase one, you're on a strict lean protein diet. This is based on a list of 72 reasonably low-fat protein-rich foods, such as chicken, turkey, eggs, fish and fat-free dairy. This is for an average of five days to achieve quick weight loss. Carbs are off limits, except for a small amount of oat bran.
    Unlike the Atkins diet, Dukan's phase one bans vegetables and seriously restricts fat. The next three phases of the plan see the gradual introduction of some fruit, veg and carbs, and eventually all foods. The aim is gradual weight loss of up to 2lb a week and to promote long-term weight management. There's no time limit to the final phase, which involves having a protein-only day once a week and taking regular exercise.",
    pros: "You can lose weight very quickly, which can be motivating. It's a very strict and prescriptive diet, which some people like. It's easy to follow, and you don't need to weigh food or count calories. Apart from keeping to low-fat, low-salt and high-protein foods, there's no restriction on how much you can eat during your first two weeks.",
    cons: "At the start of the diet, you may experience side effects such as bad breath, a dry mouth, tiredness, dizziness, insomnia and nausea from cutting out carbs. The lack of wholegrains, fruit and veg in the early stages of the diet could cause problems such as constipation.
    ",
    bda: "Rapid weight loss can be motivating, but it is unsustainable and unhealthy. The Dukan diet isn't nutritionally balanced, which is acknowledged by the fact you need a vitamin supplement and a fibre top-up in the form of oat bran. There's a danger this type of diet could increase your risk of long-term health problems if you don't stick to the rules. The diet lacks variety in the initial phases, so there's a risk you'll get bored quickly and give up. "
  },{
    name: "Paleo diet",
    intro: "The paleo diet, also known as the caveman diet, consists of foods that can be hunted and fished – such as meat and seafood – and foods that can be gathered – such as eggs, nuts, seeds, fruits, vegetables, herbs and spices. It's a regime based on the supposed eating habits of our hunter-gatherer ancestors during the paleolithic era, before the development of agriculture around 10,000 years ago. That means cereal grains including wheat, dairy, refined sugar, potatoes and salt – as well as anything processed – are strictly off the menu. There is no official 'paleo diet', but it is generally seen as a low-carb, high-protein diet, with some variations on carbohydrate and meat intake.
    Advocates say the paleo diet is a long-term healthy eating plan that can help you lose weight and reduce your risk of diabetes, heart disease, cancer and other health problems. Most studies on the paleo-type diet are small, and more long-term research is needed to show conclusively whether or not it is as effective as some people claim. One 2014 study (PDF, 790kb) found similar weight loss between participants on a paleo diet and those on a low-fat diet after two years. However, participants on the paleo diet did have slightly better levels of triglycerides, a type of fat linked to heart disease. ",
    pros: "The paleo diet encourages you to eat less processed food and more fruit and vegetables. Reducing your consumption of high-calorie foods will reduce your calorie intake and help you lose weight. The diet is simple and doesn't involve calorie counting. Some plans go by the '80/20' rule, where you'll get 99% of the benefits of the paleo diet if you adhere to it 80% of the time. This flexibility can make the diet easier to stick to, so you are more likely to be successful.",
    cons: "There are no accurate records of the diet of our Stone Age ancestors, so the paleo diet is largely based on educated guesses, and its health claims lack scientific evidence. Most versions of the diet encourage large amounts of meat, which runs counter to current health advice on meat consumption. Many versions ban dairy products and wholegrains, which form part of a healthy, balanced diet. Like all high-protein diets, the paleo can be expensive, depending on your choice of meat cuts. It's impossible to follow without eating meat, seafood or eggs, so it's not one for vegetarians!
    ",
    bda: "Most versions of the paleo diet exclude key food groups, raising the potential for nutritional deficiencies unless careful substitutions are made, and dietary supplements may be necessary. The diet has some positive aspects, so an adapted version that doesn't ban any food groups – such as wholegrains, dairy and legumes – would be a better choice. The diet lacks variety, so there's a risk you'll get bored quickly and give up. If you want to copy your paleolithic ancestors, you're better off mimicking their activity levels, rather than their alleged diet."
  },{
    name: "New Atkins diet",
    intro: "The Atkins diet promises to turn your body into a fat-burning machine. The theory is that by starving yourself of carbohydrates, your body will start burning fat for energy. During the first phase of the diet, designed for rapid weight loss, you're on a protein-rich diet with no restrictions on fat and a daily carb allowance of 20-25g.
    During the next three phases, the weight loss is likely to be more gradual and regular exercise is encouraged. More carbs are introduced to your diet with the aim of working out what your ideal carb intake is to maintain a healthy weight for life. Phase one is designed to help you lose up to 15lb in two weeks, reducing to 2-3lb during phase two.",
    pros: "You can lose weight very quickly, which can be motivating. The diet also encourages people to cut out most processed carbs and alcohol. With its diet of red meat, butter, cream, cheese and mayonnaise, it's one of the diets that appeals most to men.",
    cons: "Initial side effects can include bad breath, a dry mouth, tiredness, dizziness, insomnia, nausea and constipation from cutting out carbs, and potential for lower fibre intake. The high intake of saturated fat may increase your risk of heart disease, and there are concerns about the recommendation to add salt.
    ",
    bda: "The amount of processed meat, red meat and saturated fat in this type of diet is an issue, as is the advice to add salt, which all contradict current health advice. Some could still find it complicated and time consuming, but the promise of initial rapid weight loss may appeal to and motivate some.  "
  },{
    name: "Alkaline diet",
    intro: "The alkaline diet is based on the idea that modern diets cause our body to produce too much acid. The theory is that excess acid in the body is turned into fat, leading to weight gain. High acidity levels have also been blamed on conditions such as arthritis, osteoporosis, tiredness, and kidney and liver disorders.
    The diet involves cutting back on acid-producing foods such as meat, wheat and other grains, refined sugar, dairy products, caffeine, alcohol and processed foods in favour of 'alkaline foods', which reduce the body's acidity levels. This translates into plenty of fruit and vegetables. The idea is that an alkaline diet helps maintain the body's acidity at healthy levels. There are different versions of the alkaline diet. Some followers adopt the '80/20 rule', consisting of a diet based on 80% fruit and veg and 20% grains and protein.
    Originally developed to help prevent kidney stones and urine infections by using diet to adjust the acidity levels in the urine, there is little evidence to support the diet's more recent health claims. The weight loss observed among followers is more likely to be the result of eating plenty of fruit and vegetables and cutting down on sugar, alcohol and processed foods, which is standard healthy weight loss advice.",
    pros: "The diet contains plenty of good healthy eating advice, such as cutting down on meat, avoiding sugar, alcohol and processed foods, and eating more fruit and veg, nuts, seeds and legumes. This means you will be cutting out foods you may normally eat and replacing them with healthier choices, which will also reduce your calorie intake.",
    cons: "Your body regulates its acidity levels, regardless of diet. When cutting down on dairy products such as milk, cheese and yoghurt, you need to find other calcium substitutes, as cutting out an entire food group is never a good idea. Getting to grips with what you can and can't eat on the diet can be time consuming, particularly in the beginning.",
    bda: "The theory of the alkaline diet is that eating certain foods can help maintain the body's ideal pH balance (acidity levels) to improve overall health. But the body maintains its pH balance regardless of diet. The diet lacks evidence, and some versions that advise cutting out entire food groups should be avoided. The more balanced versions of the diet provide variety and include all the food groups. If you are going to try the alkaline diet, choose a balanced plan, stick to it to the letter, and stay clear of supplements and other diet-related gimmicks.  "
  },{
    name: "Cambridge diet",
    intro: "The Cambridge Weight Plans are based around buying and eating a range of meal-replacement products with the promise of rapid weight loss. There are six flexible diet plans ranging from 415 calories to 1,500 calories or more a day, depending on your weight loss goal. There is also a long-term weight management programme. The bars, soups, porridges and shakes can be used as your sole source of nutrition or together with low-calorie regular meals. While on the programme, you receive advice and support on healthy eating and exercise from a Cambridge adviser.",
    pros: "Many people on very low calorie diets find the weight loss to be sudden and quite dramatic. The meal replacements are all nutritionally balanced, so you're likely to be getting all the vitamins and minerals you need, albeit not from real food.",
    cons: "Initial side effects can include bad breath, a dry mouth, tiredness, dizziness, insomnia, nausea and constipation from cutting down on carbs and fibre. The hardest part of the plan is sticking to it. Giving up normal meals and swapping them for a snack bar or a shake can be boring and feel socially isolating. This isn't a plan you can stick to in the long term.
    ",
    bda: "You need to like the meal replacement products to stay with the plan. Rapid weight loss can be motivating, but it is unsustainable. A very low calorie diet that involves eating 1,000 calories a day or fewer should not be followed for more than 12 continuous weeks. If you are eating fewer than 600 calories a day, you should have medical supervision."
  },{
    name: "South Beach Diet",
    intro: "The South Beach Diet is a low-GI diet originally developed for heart patients in the US. There's no calorie counting and no limits on portions. You're encouraged to eat three meals and two snacks a day, and follow an exercise plan. People who have more than 10lb to lose start with phase one. This is a two-week quick weight loss regime where you eat lean protein, including meat, fish and poultry, as well as some low-GI vegetables and unsaturated fats. Low-GI carbs are re-introduced during phases two and three, which encourage gradual and sustainable weight loss.",
    pros: "If you can avoid phase one and start on phase two, there are fewer dietary restrictions in the rest of the plan than some other popular diets. After phase one, the diet broadly follows the basic principles of healthy eating. No major food groups are eliminated and plenty of fruit, veg and low-GI carbs are recommended.",
    cons: "The severe dietary restrictions of phase one may leave you feeling weak and you will miss out on some vitamins, minerals and fibre. You may initially experience side effects such as bad breath, a dry mouth, tiredness, dizziness, insomnia, nausea and constipation.",
    bda: "The first two weeks are the most difficult to get through. We're concerned this diet promises such a large weight loss – up to 13lb – in the first two weeks. This, however, won't be all fat. Some of the weight loss will include water and carbs, both of which will be replaced when you begin eating more normally. Once you get past the initial phase, the diet follows the basic principles of healthy eating and should provide the nutrients you need to stay healthy."
  },{
    name: "Slimming World diet",
    intro: "Slimming World's weight loss plan encourages you to swap high-fat foods for low-fat foods that are naturally filling. You choose your food from a list of low-fat foods they call 'Free Foods', such as fruit, vegetables, pasta, potatoes, rice, lean meat, fish and eggs, which you can eat in unlimited amounts. There's no calorie counting, no foods are banned, and you're still allowed the occasional treat. You can get support from fellow slimmers at weekly group meetings and follow an exercise plan to become gradually more active. The plan is designed to help you lose about 1-2lb a week.",
    pros: "No foods are banned, so meals offer balance and variety and are family-friendly. The portion size from each food group will vary depending on which plan you follow. The 'Body Magic' booklet they provide gives ideas to help you raise your activity levels. Meeting as a group can provide valuable support.",
    cons: "Slimming World doesn't educate you about calories. Without learning about calories and portion sizes, you may struggle to keep the weight off in the long term when you come off the programme.",
    bda: "The group meetings encourage members to share successes, ideas and recipes with each other, but they may not appeal to everyone. While the meal plans may lack some flexibility, they are generally balanced. However, without learning about calories and portion sizes, you may struggle to make healthy choices once you've left the programme.  "
  },{
    name: "Slim-Fast diet",
    intro: "The Slim-Fast diet is a low-calorie meal replacement plan for people with a BMI of 25 and over. It uses Slim-Fast's range of products. The plan recommends three snacks a day from an extensive list, including crisps and chocolate, two meal replacement shakes or bars, and one regular meal taken from a list of recipes on the Slim-Fast website. You can stay on the diet for as long as you want, depending on your weight loss goal. Once reached, you're advised to have one meal replacement shake a day, up to two low-fat snacks and two healthy meals. The plan is designed to help you lose about 1-2lb a week and you can follow the diet for as long as you want.",
    pros: "Meal replacement diets can be effective at helping some people lose weight and keep it off. The plan is convenient, as the products take the guesswork out of portion control and calorie counting. No foods are forbidden, although you are encouraged to eat lean protein, fruit and vegetables",
    cons: "On their own, meal replacement diets do little to educate people about their eating habits and change their behaviour. There's a risk of putting the weight back on again once you stop using the products. You may find it hard to get your 5 A DAY of fruit and veg without careful planning.",
    bda: "If you don't like the taste of the meal replacement products, you won't stay with the plan. The Slim-Fast plan can be useful to kickstart your weight loss regime, but it's important that you make full use of the online support to learn about the principles of healthy eating and how to manage everyday food and drink.  "
  },{
    name: "LighterLife diet",
    intro: "The LighterLife weight loss plans combine a very low-calorie meal replacement diet with weekly counselling. With LighterLife Total, for people with a BMI of 30 or more, you eat four food packs a day, consisting of shakes, soups, mousses or bars, and no conventional food. LighterLife Lite, for those with a BMI of 25-30, involves eating three food packs a day, plus one meal from a list of approved foods. You stay on the plans until you reach your target weight. The meal plans can lead to very rapid weight loss, and you're advised to see your GP before starting. How long you stay on the diet depends on how much weight you have to lose.",
    pros: "The counselling can help you understand your relationship with food, so hopefully you can make lasting changes to keep the weight off for good. With the meal replacements, there's no weighing or measuring, so it's a hassle-free approach to weight loss.",
    cons: "Initial side effects of the diet can include bad breath, a dry mouth, tiredness, dizziness, insomnia, nausea and constipation from cutting down on carbs and fibre. Surviving on a strict diet of shakes and soups and other meal replacements isn't much fun, and can feel socially isolating.",
    bda: "Rapid weight loss can be motivating, but it is unsustainable. LighterLife's very low calorie diet and its counselling component may work for some, particularly people who have struggled to lose weight for years, have health problems as a result of their weight, and are clinically obese with a BMI of more than 30. A very low calorie diet that involves eating 1,000 calories a day or fewer should not be followed for more than 12 continuous weeks. If you are eating fewer than 600 calories a day, you should have medical supervision. "
  },{
    name: "WeightWatchers diet",
    intro: "The WeightWatchers plan is based on the SmartPoints system, which gives a value to foods and drink based on protein, carbs, fat and fibre content. It is essentially a calorie-controlled diet where you get a personal daily SmartPoints allowance, which you can use how you like. There's no limit on the amount of fruit and most veg you can eat. You also get a weekly SmartPoints safety net in case you go over your allowance, as well as an individual exercise plan. The weekly meetings and confidential weigh-ins provide support and extra motivation to encourage long-term behaviour change. The plan is designed to help you lose up to 2lb a week.",
    pros: "No foods are banned, so you can eat and drink what you want provided you stick to your points allowance. The SmartPoints system is easier to follow for some than calorie counting, and less restrictive than other plans. This is because it introduces a safety net of points, which can be saved up for a special occasion, such as a night out, a small amount of alcohol, or treats.",
    cons: "When you begin, working out the points system can be just as time consuming as simply counting calories. Some people feel pressured into purchasing WeightWatchers-branded foods.",
    bda: "The SmartPoints plan is generally well balanced and can be a foundation for long-term changes in dietary habits. The support group approach can help keep people motivated and educate them about healthy eating. But it's vital that you make the connection between the points system and calories if you want to avoid putting the weight back on once you leave the programme. "
  },{
    name: "Rosemary Conley diet",
    intro: "Rosemary Conley's Diet and Fitness plans combine a low-fat, low-GI diet with regular exercise. You can follow her recipes or her various diets and fitness programmes. You're encouraged to eat food with 5% or less fat, with the exception of oily fish, porridge oats and lean meat. Her online weight loss club has a range of tools and videos covering cooking classes, medical, psychological and nutritional advice, plus exercises for all fitness levels. There is also support and motivation from trained coaches. You learn about calorie counting and portion size, which can help you sustain your weight loss beyond the programme. The diets are designed to help you lose a stone in seven weeks and encourage lifestyle change. How long you stay on the plan depends on your weight loss goal.",
    pros: "The programme is based around calories, with a focus on cutting fat. The 'portion pots' – which are used to measure foods such as rice, cereal, pasta and baked beans – teach you about portion control. Physical activity is an integral part of the weight loss plan, with exercise videos suitable for all ages, sizes and abilities offered online.",
    cons: "Some low-fat products aren't necessarily healthier, as they can still be high in sugar and calories. It's unrealistic to expect people to go out with their portion pots, which means portion control may be tricky away from the home.",
    bda: "The diet and exercise plans offer a balanced approach to weight loss that teaches you about portion size, the importance of regular exercise and making healthier choices. The educational element is very useful for long-term weight management once you have left the programme. "
  },
  ])
